### ISSUE TITLE
Heads up! Deprecated supported features values which will be removed in HA Core 2025.1.

### ISSUE THREAD

**Issue by Dualdriven** [ksya/ha-nefiteasy#332] opened 2024-08-08 10:35 UTC
![image](https://github.com/user-attachments/assets/d2d4b991-a253-4a99-8d9d-5e2f5536f6fb)

Just a heads up.

**Comment by RobBie1221** [comment] 2024-08-08 10:37
Duplicate of #317

**Closed by RobBie1221** 2024-08-08 10:37 UTC
