### ISSUE TITLE
custom_components.nefiteasy.climate.NefitThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by sanderlv** [ksya/ha-nefiteasy#317] opened 2024-05-02 17:44 UTC
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1632
First occurred: 19:39:14 (1 occurrences)
Last logged: 19:39:14

Entity None (<class 'custom_components.nefiteasy.climate.NefitThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>, please create a bug report at https://github.com/ksya/ha-nefiteasy/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by sanderlv** [comment] 2024-05-02 17:48
And some more :-(

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:206
integration: Climate (documentation, issues)
First occurred: 19:46:03 (25 occurrences)
Last logged: 19:46:04

CURRENT_HVAC_HEAT was used from nefiteasy, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please report it to the author of the 'nefiteasy' custom integration
CURRENT_HVAC_IDLE was used from nefiteasy, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'nefiteasy' custom integration
HVAC_MODE_HEAT was used from nefiteasy, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'nefiteasy' custom integration
SUPPORT_PRESET_MODE was used from nefiteasy, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'nefiteasy' custom integration
SUPPORT_TARGET_TEMPERATURE was used from nefiteasy, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'nefiteasy' custom integration

**Comment by BVGorp** [comment] 2024-05-07 08:31
duplicate of https://github.com/ksya/ha-nefiteasy/issues/288

**Closed** 2024-08-14 18:51 UTC

**Comment by RobBie1221** [comment] 2024-08-14 19:27
Please test with version 0.4.4 and check if all the warnings are gone (I can't test as I don't have a device anymore). If there are still warnings, please create a new issue and share the logs.

**Comment by ChefkeGremmen** [comment] 2024-08-15 04:42
Just upgraded and the warnings in the log are gone. Keeping an eye on it the next couple of days. Thanks Rob!
